# Generated by Django 4.2.5 on 2024-01-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('react', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
